
#variables:
#  S3_BUCKET_NAME: "freenlg.org"

stages:
  #- build
  #- test
  - doc
  #- deploy

.build:
  stage: build
  image: sandrokeil/typescript
  cache:
    paths:
      - packages/*/node_modules
    untracked: true
  script:
    - npm install -g pegjs
    - npm install -g lerna
    - lerna bootstrap --concurrency 8
    - lerna run build
    - lerna run test
  artifacts:
    paths:
      - packages/*/resources_pub
      - packages/*/dist
    expire_in: 1 week

doc:
  stage: doc
  image: asciidoctor/docker-asciidoctor
  script:
    - apt install -y npm
    - npm install -g lerna
    - lerna run doc  
  artifacts:
    paths:
      - packages/*/doc_output
    expire_in: 1 week

