
#variables:
#  S3_BUCKET_NAME: "freenlg.org"

stages:
  - build
  #- test
  #- doc
  #- deploy

build:
  stage: build
  image: sandrokeil/typescript
  cache:
    paths:
      - packages/*/node_modules
      untracked: true
  script:
    - npm install -g pegjs
    - npm install -g lerna
    - lerna bootstrap --concurrency 8
    - lerna run build
    - lerna run test
  artifacts:
    paths:
      - packages/*/resources_pub/
  
