# whitelist
branches:
  only:
    - master
    - packaging

language: node_js
node_js:
  - "node"

install:
  - npm install --global lerna
  - lerna bootstrap

script:
  - lerna run build
  - lerna run test

