sudo: true

# whitelist
branches:
  only:
    - master
    - packaging

language: node_js
node_js:
  - "node"

before_install:
  - sudo apt-get -qq update
  # for doc gen
  - sudo apt-get install -y asciidoctor
  - sudo apt-get install -y ruby
  - gem install asciidoctor-pdf --pre
  # for S3
  - sudo apt-get install -y python3-pip
  - sudo pip install awscli
  # for npm
  #- pwd
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /home/travis/.npmrc


install:
  - npm install --global lerna
  - lerna bootstrap

script:
  - lerna run build
  - lerna run test
  - lerna run doc

after_script:
  # doc
  - lerna run publish:doc
  # npm
  - npm set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
  - npm config ls -l
  - cat /home/travis/.npmrc
  - lerna run publish
