# whitelist
branches:
  only:
    - master
    - packaging

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y asciidoctor
  - sudo apt-get install -y ruby
  - gem install asciidoctor-pdf --pre

install:
  - npm install --global lerna
  - lerna bootstrap

script:
  - lerna run build
  - lerna run test
  - lerna run doc
